export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  MFA_REQUIRED: "MFA_REQUIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  EVENT_NOT_JOINABLE: "EVENT_NOT_JOINABLE",
  EVENT_ALREADY_STARTED: "EVENT_ALREADY_STARTED",
  DUPLICATE_ANSWER: "DUPLICATE_ANSWER",
  ANSWER_WINDOW_CLOSED: "ANSWER_WINDOW_CLOSED",
  SOCKET_UNAUTHENTICATED: "SOCKET_UNAUTHENTICATED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
